#######################################################
# 
# CR800File.py
# Python implementation of the Class CR800File
# Generated by Enterprise Architect
# Created on:      09-Jul-2017 21:20:01
# Original author: xmalet
# 
#######################################################
from sensor_file.file_reader.abstract_file_reader import AbstractFileReader

class CR800File(AbstractFileReader):
    pass