#######################################################
# 
# SolinstXLEFile.py
# Python implementation of the Class SolinstXLEFile
# Generated by Enterprise Architect
# Created on:      09-Jul-2017 21:20:14
# Original author: Laptop
# 
#######################################################
from sensor_files.file_reader.FileReader import SensorFileReader

class SolinstXLEFile(SensorFileReader):
    def read_file():
        pass