#######################################################
# 
# SolinstCSVFile.py
# Python implementation of the Class SolinstCSVFile
# Generated by Enterprise Architect
# Created on:      09-Jul-2017 21:20:06
# Original author: Laptop
# 
#######################################################
from sensor_files.file_reader.FileReader import SensorFileReader

class SolinstCSVFile(SensorFileReader):
    def read_file():
        pass