# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'U:\Programmation\ogc_om_interface\gui\pyqt_ui\spatial_sampling_feature.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(446, 396)
        self.gridLayout = QtGui.QGridLayout(Form)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.GB_SCR = QtGui.QGroupBox(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GB_SCR.sizePolicy().hasHeightForWidth())
        self.GB_SCR.setSizePolicy(sizePolicy)
        self.GB_SCR.setMinimumSize(QtCore.QSize(0, 150))
        self.GB_SCR.setMaximumSize(QtCore.QSize(350, 171))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.GB_SCR.setFont(font)
        self.GB_SCR.setAutoFillBackground(True)
        self.GB_SCR.setObjectName(_fromUtf8("GB_SCR"))
        self.formLayout_2 = QtGui.QFormLayout(self.GB_SCR)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_4 = QtGui.QLabel(self.GB_SCR)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_4)
        self.LE_SCRid = QtGui.QLineEdit(self.GB_SCR)
        self.LE_SCRid.setEnabled(True)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.LE_SCRid.setFont(font)
        self.LE_SCRid.setReadOnly(True)
        self.LE_SCRid.setObjectName(_fromUtf8("LE_SCRid"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.LE_SCRid)
        self.label_5 = QtGui.QLabel(self.GB_SCR)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_5)
        self.LE_nomSCR = QtGui.QLineEdit(self.GB_SCR)
        self.LE_nomSCR.setEnabled(True)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.LE_nomSCR.setFont(font)
        self.LE_nomSCR.setReadOnly(True)
        self.LE_nomSCR.setObjectName(_fromUtf8("LE_nomSCR"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.LE_nomSCR)
        self.label_12 = QtGui.QLabel(self.GB_SCR)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_12)
        self.LE_scr_unit = QtGui.QLineEdit(self.GB_SCR)
        self.LE_scr_unit.setEnabled(True)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.LE_scr_unit.setFont(font)
        self.LE_scr_unit.setInputMask(_fromUtf8(""))
        self.LE_scr_unit.setReadOnly(True)
        self.LE_scr_unit.setObjectName(_fromUtf8("LE_scr_unit"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.LE_scr_unit)
        self.btn_findSCR = QtGui.QPushButton(self.GB_SCR)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btn_findSCR.setFont(font)
        self.btn_findSCR.setObjectName(_fromUtf8("btn_findSCR"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.SpanningRole, self.btn_findSCR)
        self.gridLayout.addWidget(self.GB_SCR, 0, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(Form)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setAutoFillBackground(True)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_8 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout.addWidget(self.label_8)
        self.PT_note_xy = QtGui.QTextEdit(self.groupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.PT_note_xy.setFont(font)
        self.PT_note_xy.setObjectName(_fromUtf8("PT_note_xy"))
        self.verticalLayout.addWidget(self.PT_note_xy)
        self.label_10 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout.addWidget(self.label_10)
        self.PT_note_z = QtGui.QTextEdit(self.groupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.PT_note_z.setFont(font)
        self.PT_note_z.setObjectName(_fromUtf8("PT_note_z"))
        self.verticalLayout.addWidget(self.PT_note_z)
        self.gridLayout.addWidget(self.groupBox, 0, 1, 2, 1)
        self.GB_Coordonnees = QtGui.QGroupBox(Form)
        self.GB_Coordonnees.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GB_Coordonnees.sizePolicy().hasHeightForWidth())
        self.GB_Coordonnees.setSizePolicy(sizePolicy)
        self.GB_Coordonnees.setMinimumSize(QtCore.QSize(0, 0))
        self.GB_Coordonnees.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.GB_Coordonnees.setFont(font)
        self.GB_Coordonnees.setAutoFillBackground(True)
        self.GB_Coordonnees.setObjectName(_fromUtf8("GB_Coordonnees"))
        self.formLayout = QtGui.QFormLayout(self.GB_Coordonnees)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.ckb_degree = QtGui.QCheckBox(self.GB_Coordonnees)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.ckb_degree.setFont(font)
        self.ckb_degree.setObjectName(_fromUtf8("ckb_degree"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.SpanningRole, self.ckb_degree)
        self.lbl_X = QtGui.QLabel(self.GB_Coordonnees)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lbl_X.setFont(font)
        self.lbl_X.setObjectName(_fromUtf8("lbl_X"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.lbl_X)
        self.LE_X = QtGui.QLineEdit(self.GB_Coordonnees)
        self.LE_X.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.LE_X.setFont(font)
        self.LE_X.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.LE_X.setObjectName(_fromUtf8("LE_X"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.LE_X)
        self.lbl_Y = QtGui.QLabel(self.GB_Coordonnees)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lbl_Y.setFont(font)
        self.lbl_Y.setObjectName(_fromUtf8("lbl_Y"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.lbl_Y)
        self.LE_Y = QtGui.QLineEdit(self.GB_Coordonnees)
        self.LE_Y.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.LE_Y.setFont(font)
        self.LE_Y.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.LE_Y.setObjectName(_fromUtf8("LE_Y"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.LE_Y)
        self.lbl_Z = QtGui.QLabel(self.GB_Coordonnees)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lbl_Z.setFont(font)
        self.lbl_Z.setObjectName(_fromUtf8("lbl_Z"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.lbl_Z)
        self.LE_Z = QtGui.QLineEdit(self.GB_Coordonnees)
        self.LE_Z.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.LE_Z.setFont(font)
        self.LE_Z.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.LE_Z.setObjectName(_fromUtf8("LE_Z"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.LE_Z)
        self.label_7 = QtGui.QLabel(self.GB_Coordonnees)
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.SpanningRole, self.label_7)
        self.CB_type_XY = QtGui.QComboBox(self.GB_Coordonnees)
        self.CB_type_XY.setMinimumSize(QtCore.QSize(0, 20))
        self.CB_type_XY.setMaximumSize(QtCore.QSize(16777215, 20))
        self.CB_type_XY.setObjectName(_fromUtf8("CB_type_XY"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.SpanningRole, self.CB_type_XY)
        self.ckBox_typeZ = QtGui.QCheckBox(self.GB_Coordonnees)
        self.ckBox_typeZ.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.ckBox_typeZ.setFont(font)
        self.ckBox_typeZ.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ckBox_typeZ.setChecked(True)
        self.ckBox_typeZ.setObjectName(_fromUtf8("ckBox_typeZ"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.SpanningRole, self.ckBox_typeZ)
        self.CB_type_Z = QtGui.QComboBox(self.GB_Coordonnees)
        self.CB_type_Z.setMinimumSize(QtCore.QSize(0, 20))
        self.CB_type_Z.setMaximumSize(QtCore.QSize(16777215, 20))
        self.CB_type_Z.setObjectName(_fromUtf8("CB_type_Z"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.SpanningRole, self.CB_type_Z)
        self.gridLayout.addWidget(self.GB_Coordonnees, 1, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.GB_SCR.setTitle(_translate("Form", "Système de coordonnées de référence", None))
        self.label_4.setText(_translate("Form", "SCR ID", None))
        self.label_5.setText(_translate("Form", "Nom du SCR", None))
        self.label_12.setText(_translate("Form", "Unité", None))
        self.btn_findSCR.setText(_translate("Form", "Trouver un SCR", None))
        self.groupBox.setTitle(_translate("Form", "Note sur les coordonnées", None))
        self.label_8.setText(_translate("Form", "Note surla coordonnée X,Y", None))
        self.label_10.setText(_translate("Form", "Note surla coordonnée z", None))
        self.GB_Coordonnees.setTitle(_translate("Form", "Coordonnées", None))
        self.ckb_degree.setText(_translate("Form", "En degré uniquement", None))
        self.lbl_X.setText(_translate("Form", "X", None))
        self.lbl_Y.setText(_translate("Form", "Y", None))
        self.lbl_Z.setText(_translate("Form", "Z", None))
        self.label_7.setText(_translate("Form", "Type de coordonnée X, Y", None))
        self.ckBox_typeZ.setText(_translate("Form", "Type de coordonnées Z (cocher si idem à X,Y)", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Form = QtGui.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

