# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'U:\Programmation\ogc_om_interface\gui\pyqt_ui\sampling_feature_toolbox.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8


    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(458, 921)
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.toolbox_sampling_feature = QtGui.QToolBox(Form)
        self.toolbox_sampling_feature.setObjectName(_fromUtf8("toolbox_sampling_feature"))
        self.sampling_page = QtGui.QWidget()
        self.sampling_page.setGeometry(QtCore.QRect(0, -126, 423, 975))
        self.sampling_page.setObjectName(_fromUtf8("sampling_page"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.sampling_page)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.groupbox_sampling_feature = QtGui.QGroupBox(self.sampling_page)
        self.groupbox_sampling_feature.setMinimumSize(QtCore.QSize(264, 0))
        self.groupbox_sampling_feature.setObjectName(_fromUtf8("groupbox_sampling_feature"))
        self.formLayout_2 = QtGui.QFormLayout(self.groupbox_sampling_feature)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_foi_id = QtGui.QLabel(self.groupbox_sampling_feature)
        self.label_foi_id.setMinimumSize(QtCore.QSize(0, 18))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_foi_id.setFont(font)
        self.label_foi_id.setObjectName(_fromUtf8("label_foi_id"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.SpanningRole, self.label_foi_id)
        self.gb_ref = QtGui.QGroupBox(self.groupbox_sampling_feature)
        self.gb_ref.setMinimumSize(QtCore.QSize(0, 58))
        self.gb_ref.setAutoFillBackground(True)
        self.gb_ref.setFlat(False)
        self.gb_ref.setObjectName(_fromUtf8("gb_ref"))
        self.formLayout = QtGui.QFormLayout(self.gb_ref)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_ref = QtGui.QLabel(self.gb_ref)
        self.label_ref.setMinimumSize(QtCore.QSize(0, 20))
        self.label_ref.setObjectName(_fromUtf8("label_ref"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_ref)
        self.CB_ref = QtGui.QComboBox(self.gb_ref)
        self.CB_ref.setMinimumSize(QtCore.QSize(0, 20))
        self.CB_ref.setObjectName(_fromUtf8("CB_ref"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.CB_ref)
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.SpanningRole, self.gb_ref)
        self.gb_id_bd_extern = QtGui.QGroupBox(self.groupbox_sampling_feature)
        self.gb_id_bd_extern.setMinimumSize(QtCore.QSize(0, 48))
        self.gb_id_bd_extern.setAutoFillBackground(True)
        self.gb_id_bd_extern.setFlat(False)
        self.gb_id_bd_extern.setCheckable(True)
        self.gb_id_bd_extern.setChecked(False)
        self.gb_id_bd_extern.setObjectName(_fromUtf8("gb_id_bd_extern"))
        self.formLayout_3 = QtGui.QFormLayout(self.gb_id_bd_extern)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.LE_id_bd_extern = QtGui.QLineEdit(self.gb_id_bd_extern)
        self.LE_id_bd_extern.setMinimumSize(QtCore.QSize(20, 20))
        self.LE_id_bd_extern.setObjectName(_fromUtf8("LE_id_bd_extern"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.LE_id_bd_extern)
        self.label_id_bd_extern = QtGui.QLabel(self.gb_id_bd_extern)
        self.label_id_bd_extern.setMinimumSize(QtCore.QSize(0, 20))
        self.label_id_bd_extern.setObjectName(_fromUtf8("label_id_bd_extern"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_id_bd_extern)
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.SpanningRole, self.gb_id_bd_extern)
        self.label_element_type = QtGui.QLabel(self.groupbox_sampling_feature)
        self.label_element_type.setMinimumSize(QtCore.QSize(0, 20))
        self.label_element_type.setObjectName(_fromUtf8("label_element_type"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_element_type)
        self.CB_interet = QtGui.QComboBox(self.groupbox_sampling_feature)
        self.CB_interet.setMinimumSize(QtCore.QSize(0, 20))
        self.CB_interet.setObjectName(_fromUtf8("CB_interet"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.CB_interet)
        self.label_samp_name = QtGui.QLabel(self.groupbox_sampling_feature)
        self.label_samp_name.setObjectName(_fromUtf8("label_samp_name"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_samp_name)
        self.LE_sampling_name = QtGui.QLineEdit(self.groupbox_sampling_feature)
        self.LE_sampling_name.setMinimumSize(QtCore.QSize(0, 20))
        self.LE_sampling_name.setObjectName(_fromUtf8("LE_sampling_name"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.LE_sampling_name)
        self.label_date = QtGui.QLabel(self.groupbox_sampling_feature)
        self.label_date.setMinimumSize(QtCore.QSize(0, 20))
        self.label_date.setObjectName(_fromUtf8("label_date"))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_date)
        self.DTE_sampling_date = QtGui.QDateTimeEdit(self.groupbox_sampling_feature)
        self.DTE_sampling_date.setMinimumSize(QtCore.QSize(0, 20))
        self.DTE_sampling_date.setObjectName(_fromUtf8("DTE_sampling_date"))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.FieldRole, self.DTE_sampling_date)
        self.groupbox_specimen = QtGui.QGroupBox(self.groupbox_sampling_feature)
        self.groupbox_specimen.setCheckable(True)
        self.groupbox_specimen.setChecked(False)
        self.groupbox_specimen.setObjectName(_fromUtf8("groupbox_specimen"))
        self.formLayout_6 = QtGui.QFormLayout(self.groupbox_specimen)
        self.formLayout_6.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_6.setObjectName(_fromUtf8("formLayout_6"))
        self.groupbox_sampling_context = QtGui.QGroupBox(self.groupbox_specimen)
        self.groupbox_sampling_context.setMinimumSize(QtCore.QSize(0, 0))
        self.groupbox_sampling_context.setCheckable(False)
        self.groupbox_sampling_context.setObjectName(_fromUtf8("groupbox_sampling_context"))
        self.formLayout_7 = QtGui.QFormLayout(self.groupbox_sampling_context)
        self.formLayout_7.setObjectName(_fromUtf8("formLayout_7"))
        self.label_find_element = QtGui.QLabel(self.groupbox_sampling_context)
        self.label_find_element.setMinimumSize(QtCore.QSize(0, 20))
        self.label_find_element.setObjectName(_fromUtf8("label_find_element"))
        self.formLayout_7.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_find_element)
        self.LE_text_to_search = QtGui.QLineEdit(self.groupbox_sampling_context)
        self.LE_text_to_search.setMinimumSize(QtCore.QSize(0, 20))
        self.LE_text_to_search.setText(_fromUtf8(""))
        self.LE_text_to_search.setObjectName(_fromUtf8("LE_text_to_search"))
        self.formLayout_7.setWidget(1, QtGui.QFormLayout.SpanningRole, self.LE_text_to_search)
        self.CB_finded_element = QtGui.QComboBox(self.groupbox_sampling_context)
        self.CB_finded_element.setMinimumSize(QtCore.QSize(0, 20))
        self.CB_finded_element.setObjectName(_fromUtf8("CB_finded_element"))
        self.formLayout_7.setWidget(3, QtGui.QFormLayout.SpanningRole, self.CB_finded_element)
        self.label_finded_element = QtGui.QLabel(self.groupbox_sampling_context)
        self.label_finded_element.setMinimumSize(QtCore.QSize(0, 20))
        self.label_finded_element.setObjectName(_fromUtf8("label_finded_element"))
        self.formLayout_7.setWidget(2, QtGui.QFormLayout.SpanningRole, self.label_finded_element)
        self.label_type = QtGui.QLabel(self.groupbox_sampling_context)
        self.label_type.setMinimumSize(QtCore.QSize(0, 20))
        self.label_type.setObjectName(_fromUtf8("label_type"))
        self.formLayout_7.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_type)
        self.CB_relation_type = QtGui.QComboBox(self.groupbox_sampling_context)
        self.CB_relation_type.setMinimumSize(QtCore.QSize(0, 20))
        self.CB_relation_type.setObjectName(_fromUtf8("CB_relation_type"))
        self.formLayout_7.setWidget(5, QtGui.QFormLayout.SpanningRole, self.CB_relation_type)
        self.btn_box_ok_cancel = QtGui.QDialogButtonBox(self.groupbox_sampling_context)
        self.btn_box_ok_cancel.setMinimumSize(QtCore.QSize(0, 20))
        self.btn_box_ok_cancel.setStandardButtons(QtGui.QDialogButtonBox.Cancel | QtGui.QDialogButtonBox.Ok)
        self.btn_box_ok_cancel.setObjectName(_fromUtf8("btn_box_ok_cancel"))
        self.formLayout_7.setWidget(6, QtGui.QFormLayout.SpanningRole, self.btn_box_ok_cancel)
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.SpanningRole, self.groupbox_sampling_context)
        self.label_spe_mat = QtGui.QLabel(self.groupbox_specimen)
        self.label_spe_mat.setObjectName(_fromUtf8("label_spe_mat"))
        self.formLayout_6.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_spe_mat)
        self.CB_spe_material = QtGui.QComboBox(self.groupbox_specimen)
        self.CB_spe_material.setObjectName(_fromUtf8("CB_spe_material"))
        self.formLayout_6.setWidget(2, QtGui.QFormLayout.FieldRole, self.CB_spe_material)
        self.label_sample_loc = QtGui.QLabel(self.groupbox_specimen)
        self.label_sample_loc.setObjectName(_fromUtf8("label_sample_loc"))
        self.formLayout_6.setWidget(3, QtGui.QFormLayout.SpanningRole, self.label_sample_loc)
        self.label_sample_size = QtGui.QLabel(self.groupbox_specimen)
        self.label_sample_size.setObjectName(_fromUtf8("label_sample_size"))
        self.formLayout_6.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_sample_size)
        self.LE_Size_qt = QtGui.QLineEdit(self.groupbox_specimen)
        self.LE_Size_qt.setObjectName(_fromUtf8("LE_Size_qt"))
        self.formLayout_6.setWidget(6, QtGui.QFormLayout.LabelRole, self.LE_Size_qt)
        self.CB_size_unit = QtGui.QComboBox(self.groupbox_specimen)
        self.CB_size_unit.setObjectName(_fromUtf8("CB_size_unit"))
        self.formLayout_6.setWidget(6, QtGui.QFormLayout.FieldRole, self.CB_size_unit)
        self.label_sample_type = QtGui.QLabel(self.groupbox_specimen)
        self.label_sample_type.setObjectName(_fromUtf8("label_sample_type"))
        self.formLayout_6.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_sample_type)
        self.CB_sample_type = QtGui.QComboBox(self.groupbox_specimen)
        self.CB_sample_type.setObjectName(_fromUtf8("CB_sample_type"))
        self.formLayout_6.setWidget(8, QtGui.QFormLayout.SpanningRole, self.CB_sample_type)
        self.btn_create_samp_type = QtGui.QPushButton(self.groupbox_specimen)
        self.btn_create_samp_type.setObjectName(_fromUtf8("btn_create_samp_type"))
        self.formLayout_6.setWidget(9, QtGui.QFormLayout.SpanningRole, self.btn_create_samp_type)
        self.LE_current_loc = QtGui.QLineEdit(self.groupbox_specimen)
        self.LE_current_loc.setObjectName(_fromUtf8("LE_current_loc"))
        self.formLayout_6.setWidget(4, QtGui.QFormLayout.SpanningRole, self.LE_current_loc)
        self.formLayout_2.setWidget(6, QtGui.QFormLayout.SpanningRole, self.groupbox_specimen)
        self.label_note = QtGui.QLabel(self.groupbox_sampling_feature)
        self.label_note.setObjectName(_fromUtf8("label_note"))
        self.formLayout_2.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_note)
        self.PTE_note = QtGui.QPlainTextEdit(self.groupbox_sampling_feature)
        self.PTE_note.setObjectName(_fromUtf8("PTE_note"))
        self.formLayout_2.setWidget(7, QtGui.QFormLayout.FieldRole, self.PTE_note)
        self.groupBox = QtGui.QGroupBox(self.groupbox_sampling_feature)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.formLayout_5 = QtGui.QFormLayout(self.groupBox)
        self.formLayout_5.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_5.setObjectName(_fromUtf8("formLayout_5"))
        self.radio_relative_loc = QtGui.QRadioButton(self.groupBox)
        self.radio_relative_loc.setChecked(True)
        self.radio_relative_loc.setObjectName(_fromUtf8("radio_relative_loc"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.SpanningRole, self.radio_relative_loc)
        self.label_de_m = QtGui.QLabel(self.groupBox)
        self.label_de_m.setEnabled(False)
        self.label_de_m.setObjectName(_fromUtf8("label_de_m"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_de_m)
        self.LE_relative_loc_from = QtGui.QLineEdit(self.groupBox)
        self.LE_relative_loc_from.setEnabled(False)
        self.LE_relative_loc_from.setObjectName(_fromUtf8("LE_relative_loc_from"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.FieldRole, self.LE_relative_loc_from)
        self.label_a_m = QtGui.QLabel(self.groupBox)
        self.label_a_m.setEnabled(False)
        self.label_a_m.setObjectName(_fromUtf8("label_a_m"))
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_a_m)
        self.LE_relative_loc_to = QtGui.QLineEdit(self.groupBox)
        self.LE_relative_loc_to.setEnabled(False)
        self.LE_relative_loc_to.setObjectName(_fromUtf8("LE_relative_loc_to"))
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.FieldRole, self.LE_relative_loc_to)
        self.radio_geographique_loc = QtGui.QRadioButton(self.groupBox)
        self.radio_geographique_loc.setObjectName(_fromUtf8("radio_geographique_loc"))
        self.formLayout_5.setWidget(3, QtGui.QFormLayout.SpanningRole, self.radio_geographique_loc)
        self.btn_import_shapefile = QtGui.QPushButton(self.groupBox)
        self.btn_import_shapefile.setEnabled(False)
        self.btn_import_shapefile.setObjectName(_fromUtf8("btn_import_shapefile"))
        self.formLayout_5.setWidget(5, QtGui.QFormLayout.SpanningRole, self.btn_import_shapefile)
        self.btn_enter_xy = QtGui.QPushButton(self.groupBox)
        self.btn_enter_xy.setEnabled(False)
        self.btn_enter_xy.setObjectName(_fromUtf8("btn_enter_xy"))
        self.formLayout_5.setWidget(4, QtGui.QFormLayout.SpanningRole, self.btn_enter_xy)
        self.formLayout_2.setWidget(8, QtGui.QFormLayout.SpanningRole, self.groupBox)
        self.verticalLayout_3.addWidget(self.groupbox_sampling_feature)
        self.toolbox_sampling_feature.addItem(self.sampling_page, _fromUtf8(""))
        self.process_page = QtGui.QWidget()
        self.process_page.setGeometry(QtCore.QRect(0, 0, 440, 849))
        self.process_page.setObjectName(_fromUtf8("process_page"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.process_page)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gb_process = QtGui.QGroupBox(self.process_page)
        self.gb_process.setMinimumSize(QtCore.QSize(0, 185))
        self.gb_process.setObjectName(_fromUtf8("gb_process"))
        self.formLayout_4 = QtGui.QFormLayout(self.gb_process)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.label_process_type = QtGui.QLabel(self.gb_process)
        self.label_process_type.setMinimumSize(QtCore.QSize(0, 20))
        self.label_process_type.setObjectName(_fromUtf8("label_process_type"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_process_type)
        self.CB_process_type = QtGui.QComboBox(self.gb_process)
        self.CB_process_type.setMinimumSize(QtCore.QSize(0, 20))
        self.CB_process_type.setObjectName(_fromUtf8("CB_process_type"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.CB_process_type)
        self.label_finded_process = QtGui.QLabel(self.gb_process)
        self.label_finded_process.setMinimumSize(QtCore.QSize(0, 20))
        self.label_finded_process.setObjectName(_fromUtf8("label_finded_process"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_finded_process)
        self.CB_process = QtGui.QComboBox(self.gb_process)
        self.CB_process.setMinimumSize(QtCore.QSize(0, 20))
        self.CB_process.setObjectName(_fromUtf8("CB_process"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.CB_process)
        self.label_process_description = QtGui.QLabel(self.gb_process)
        self.label_process_description.setObjectName(_fromUtf8("label_process_description"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.SpanningRole, self.label_process_description)
        self.label_proces_desc = QtGui.QLabel(self.gb_process)
        self.label_proces_desc.setMinimumSize(QtCore.QSize(0, 50))
        self.label_proces_desc.setScaledContents(True)
        self.label_proces_desc.setWordWrap(True)
        self.label_proces_desc.setObjectName(_fromUtf8("label_proces_desc"))
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.SpanningRole, self.label_proces_desc)
        self.btn_create_methode = QtGui.QPushButton(self.gb_process)
        self.btn_create_methode.setMinimumSize(QtCore.QSize(0, 20))
        self.btn_create_methode.setObjectName(_fromUtf8("btn_create_methode"))
        self.formLayout_4.setWidget(4, QtGui.QFormLayout.SpanningRole, self.btn_create_methode)
        self.verticalLayout_2.addWidget(self.gb_process)
        self.toolbox_sampling_feature.addItem(self.process_page, _fromUtf8(""))
        self.verticalLayout.addWidget(self.toolbox_sampling_feature)

        self.retranslateUi(Form)
        self.toolbox_sampling_feature.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.groupbox_sampling_feature.setTitle(_translate("Form", "Information sur l\'élément", None))
        self.label_foi_id.setText(_translate("Form", "identifiant de l\'élément :", None))
        self.gb_ref.setTitle(_translate("Form", "Provenant de la donnée", None))
        self.label_ref.setText(_translate("Form", "Référence", None))
        self.gb_id_bd_extern.setTitle(_translate("Form", "Provient d\'une Base de données existante?", None))
        self.label_id_bd_extern.setText(_translate("Form", "id de base de donnée", None))
        self.label_element_type.setText(_translate("Form", "Type d\'élément", None))
        self.label_samp_name.setText(_translate("Form", "Nom de l\'élément", None))
        self.label_date.setText(_translate("Form", "Date de création de l\'élément", None))
        self.groupbox_specimen.setTitle(_translate("Form", "Est un échantillon?", None))
        self.groupbox_sampling_context.setTitle(_translate("Form", "Provenance", None))
        self.label_find_element.setText(_translate("Form", "Rechercher élément", None))
        self.LE_text_to_search.setToolTip(_translate("Form", "Appuyez sur \"Enter\" pour lancer la recherche", None))
        self.LE_text_to_search.setPlaceholderText(_translate("Form", "saisir nom", None))
        self.label_finded_element.setText(_translate("Form", "Éléments trouvés", None))
        self.label_type.setText(_translate("Form", "Type de relation", None))
        self.label_spe_mat.setText(_translate("Form", "Matériel de l\'échantillon", None))
        self.label_sample_loc.setText(_translate("Form", "Emplacement courant de l\'échantillon", None))
        self.label_sample_size.setText(_translate("Form", "Taille de l\'échantillon", None))
        self.label_sample_type.setText(_translate("Form", "Type d\'échantillon", None))
        self.btn_create_samp_type.setText(_translate("Form", "Le type d\'échantillon n\'existe pas", None))
        self.LE_current_loc.setPlaceholderText(_translate("Form", "réfrigérateur, entrepot,...", None))
        self.label_note.setText(_translate("Form", "Notes", None))
        self.groupBox.setTitle(_translate("Form", "Localisation de l\'élément", None))
        self.radio_relative_loc.setText(_translate("Form", "Position relative(de - a)", None))
        self.label_de_m.setText(_translate("Form", "De (m)", None))
        self.label_a_m.setText(_translate("Form", "A (m)", None))
        self.radio_geographique_loc.setText(_translate("Form", "Localisation géographique (coordonnée x,y,z)", None))
        self.btn_import_shapefile.setText(_translate("Form", "Importer un shapefile", None))
        self.btn_enter_xy.setText(_translate("Form", "Entrer une coordonnée", None))
        self.toolbox_sampling_feature.setItemText(self.toolbox_sampling_feature.indexOf(self.sampling_page),
                                                  _translate("Form", "Information sur l\'élément", None))
        self.gb_process.setTitle(_translate("Form", "Méthodologie associée à l\'élément", None))
        self.label_process_type.setText(_translate("Form", "Type de méthode", None))
        self.label_finded_process.setText(_translate("Form", "Méthode disponibles", None))
        self.label_process_description.setText(_translate("Form", "Description de la méthode", None))
        self.label_proces_desc.setText(_translate("Form", "TextLabel", None))
        self.btn_create_methode.setText(_translate("Form", "Méthode introuvable", None))
        self.toolbox_sampling_feature.setItemText(self.toolbox_sampling_feature.indexOf(self.process_page),
                                                  _translate("Form", "Méthodologie associée à l\'élément", None))


if __name__ == "__main__":
    import sys

    app = QtGui.QApplication(sys.argv)
    Form = QtGui.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
